### ISSUE TITLE
undefined method error

### ISSUE THREAD

**Issue by kriswallsmith** [chef-cookbooks/whitelist-node-attrs#4]
My Chef runs fail when using this recipe. The error is below. I am using Chef 12.1.1.

```
1) NoMethodError -  undefined method `key?' for "kriswallsmith.net":String
  /opt/chef/embedded/apps/chef/lib/chef/whitelist.rb:60:in `add_data'
  /opt/chef/embedded/apps/chef/lib/chef/whitelist.rb:35:in `block in filter'
  /opt/chef/embedded/apps/chef/lib/chef/whitelist.rb:34:in `each'
  /opt/chef/embedded/apps/chef/lib/chef/whitelist.rb:34:in `filter'
  /var/chef/cache/cookbooks/whitelist-node-attrs/libraries/whitelist.rb:67:in `save'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:270:in `save_updated_node'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:348:in `converge_and_save'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:448:in `run'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:52:in `load'
  /usr/bin/chef-client:52:in `<main>'
```

PS: This project's CONTRIBUTING file directs people to Jira, but Jira directs people back to GitHub.

**Comment by tas50** [comment]
We've decided to deprecate this repository since this functionality is now part of Chef 12.  Sorry for not responding earlier.
